name: doan_ltmobi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons and Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # <-- ĐÃ CẬP NHẬT

  # State & Storage
  shared_preferences: ^2.2.3

  # Database
  mongo_dart: ^0.10.5

  # UI & UX
  smooth_page_indicator: ^1.1.1 # <-- ĐÃ CẬP NHẬT
  pinput: ^4.0.0
  elegant_notification: ^2.5.1 # <-- ĐÃ CẬP NHẬT
  fl_chart: ^0.68.0
  badges: ^3.1.2
  flutter_timer_countdown: ^1.0.7

  # Utilities
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  mailer: ^6.1.0
  random_string: ^2.3.1
  crypto: ^3.0.7 # <-- ĐÃ CẬP NHẬT
  http: ^1.2.1 # <-- ĐÃ CẬP NHẬT

  # Payment Integrations
  flutter_paypal_payment: ^1.0.8 # <-- ĐÃ CẬP NHẬT
  flutter_inappwebview: ^6.0.0
  qr_flutter: ^4.1.0

  # Google Location / Maps
  google_place: ^0.4.7
  geolocator: ^12.0.0
  geocoding: ^4.0.0 # <-- ĐÃ CẬP NHẬT

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # <-- ĐÃ CẬP NHẬT
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon_app.png"
  min_sdk_android: 21